language: node_js
node_js:
  - "6.2.2"
cache:
  directories:
    - node_modules
script:
  - ./scripts/run-travis-tests.sh
after_success:
  - ./scripts/is-release-branch.sh && npm run clean && npm run build && ./scripts/deploy-to-gh-pages.sh
